[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
let g:python3_host_prog = $PYENV_ROOT . '/shims/python3'
'''
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
"<Nop>は無効化を意味する
nmap [denite] <Nop>
map s [denite]

" プロジェクト内のファイル検索
nmap <silent> [denite]p :<C-u>Denite file_rec -highlight-mode-insert=Search<CR>
" バッファに展開中のファイル検索
nmap <silent> [denite]b :<C-u>Denite buffer -mode=normal <CR>
" ファイル内の関数/クラス等の検索
nmap <silent> [denite]y :<C-u>Denite file_old <CR>
nmap <silent> [denite]w :<C-u>DeniteCursorWord line<CR>
nmap <silent> [denite]s :<C-u>Denite line<CR>
nmap <silent> [denite]h :<C-u>Denite help<CR>
call denite#custom#map('insert', 'jj', '<denite:enter_mode:normal>', 'noremap')
'''
[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
let g:winresizer_start_key = '<C-T>'
'''
