#########################################
# Dein plugin manager settings
#########################################
[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
let g:python_host_prog = expand('~/.pyenv/versions/2.7.13/bin/python2')
let g:python3_host_prog = expand('~/.pyenv/versions/3.7.2/bin/python3')
let g:ruby_host_prog = $HOME . '/.rbenv/shims/ruby'
autocmd VimEnter * call dein#call_hook('post_source')
'''

#########################################
# Change window's size settings
#########################################
[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
nnoremap <space>t :WinResizerStartResize<CR>
'''

#########################################
# Nerdtree settings
#########################################
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
function MyNerdToggle()
    if &filetype == 'nerdtree'
        :NERDTreeToggle
    else
        :NERDTreeFind
    endif
endfunction

nnoremap <silent> <space>b :call MyNerdToggle()<CR>
'''
[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
hook_add = '''
let g:NERDTreeLimitedSyntax = 1
let g:NERDTreeMapOpenVSplit = 'v'
let g:NERDTreeQuitOnOpen = 1
'''

#########################################
# Dispaly idnent vertically line
#########################################
[[plugins]]
repo = 'Yggdroot/indentLine'

hook_add = '''
nnoremap <silent> <space>it :IndentLinesToggle<CR>
let g:indentLine_color_term = 113
'''

#########################################
# Add Pairs
#########################################
[[plugins]]
repo = 'jiangmiao/auto-pairs'

#########################################
# Comment out
#########################################
[[plugins]]
repo = 'tpope/vim-commentary'

#########################################
# Syntac highlight
#########################################
[[plugins]]
repo = 'sheerun/vim-polyglot'

#########################################
# Surround settings
#########################################
[[plugins]]
repo = 'tpope/vim-surround'

[[plugin]]
repo = 'tpope/vim-repeat'

#########################################
# To make git even in vim
#########################################
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
nmap [fugitive] <Nop>
map <C-g> [fugitive]
nmap <silent> [fugitive]s :Gstatus<CR>
nmap <silent> [fugitive]d :Gdiff<CR>
nmap <silent> [fugitive]b :Gblame<CR>
nmap <silent> [fugitive]l :Glog<CR>
nmap <silent> [fugitive]r :Gread<CR>
'''
