######################################### Denite
#########################################
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  noremap [denite] <Nop>
  map s [denite]

  " mapping
  nnoremap <silent> [denite]p :<C-u>DeniteProjectDir file/rec -start-filter=v:true<CR>
  nnoremap <silent> [denite]r :<C-u>DeniteBufferDir file/rec -start-filter=v:true<CR>
  nnoremap <silent> [denite]b :<C-u>Denite buffer -start-filter=v:true<CR>
  nnoremap <silent> [denite]y :<C-u>Denite file/old -start-filter=v:true<CR>
  nnoremap <silent> [denite]s :<C-u>DeniteCursorWord grep <CR>
  nnoremap <silent> [denite]w :<C-u>DeniteProjectDir grep <CR>
  nnoremap <silent> [denite]c :<C-u>DeniteProjectDir colorscheme -start-filter=v:true<CR>
  nnoremap <silent> [denite]h :<C-u>Denite help -start-filter=v:true<CR>

" Define mappings
	autocmd FileType denite call s:denite_my_settings()
	function! s:denite_my_settings()
	  nnoremap <silent><buffer><expr> <CR> denite#do_map('do_action')

    " Open a selected file with split or vsplit
	  nnoremap <silent><buffer><expr> v denite#do_map('do_action', 'vsplit')
	  nnoremap <silent><buffer><expr> s denite#do_map('do_action', 'split')

	  nnoremap <silent><buffer><expr> d denite#do_map('do_action', 'delete')
	  nnoremap <silent><buffer><expr> p denite#do_map('do_action', 'preview')
	  nnoremap <silent><buffer><expr> q denite#do_map('quit')
	  nnoremap <silent><buffer><expr> i denite#do_map('open_filter_buffer')
	  nnoremap <silent><buffer><expr> <Space> denite#do_map('toggle_select').'j'
	endfunction

  " Color settings
  autocmd VimEnter,ColorScheme * highlight NormalFloat ctermfg=DarkGray ctermbg=Gray
  autocmd VimEnter,ColorScheme * highlight Underlined guifg=#ff0000 guibg=NONE
  autocmd VimEnter,ColorScheme * highlight Search guifg=#ff0000 guibg=NONE
'''

hook_source = '''
  " Define ignore_globs
  let s:ignore_globs = [
    \ '.git/', '.gomi/', '.undo/',
    \ 'images/', '*.o', '*.make',
    \ '*.min.*', 'img/', 'fonts/',
    \ '.DS_Store', '.eslintcache',
    \ '.npm', 'node_modules/', 'jspm_packages/',
    \ 'build/Release', '.lock-wscript', 'bower_components',
    \ '.grunt', '.nyc_output', 'coverage',
    \ 'lib-cov', '*.pid', 'pids', 'venv/',
    \ '*.seed', '*.pid.lock', 'logs',
    \ '*.log', 'npm-debug.log*', 'yarn-debug.log',
    \ 'yarn-error.log', '*.?*cache*', '*css.map',
    \ '*.class', '.ropeproject/', '__pycache__/',
  \ ]

	" Change file/rec
  call denite#custom#var('file/rec', 'command', [
    \ 'ag',
    \ '--follow',
    \ ] + map(deepcopy(s:ignore_globs), { k, v -> '--ignore=' . v }) + [
    \ '--nocolor',
    \ '--nogroup',
    \ '-g',
    \ ''
  \ ])

	" Change file/old
  call denite#custom#var('file/old', 'command', [
    \ 'ag',
    \ '--follow',
    \ ] + map(deepcopy(s:ignore_globs), { k, v -> '--ignore=' . v }) + [
    \ '--nocolor',
    \ '--nogroup',
    \ '-g',
    \ ''
  \ ])

  " Change matcher
  call denite#custom#source('file/rec', 'matchers', ['matcher/cpsm'])
  call denite#custom#source('file/old', 'matchers', ['matcher/cpsm'])
  call denite#custom#source('grep', 'matchers', ['matcher/cpsm'])

  " Change ignore_globs
  call denite#custom#filter('matcher/ignore_globs', 'ignore_globs', s:ignore_globs)

	" Ag command on grep source
	call denite#custom#var('grep', 'command', ['ag'])
	call denite#custom#var('grep', 'default_opts', ['-i', '--vimgrep'])
	call denite#custom#var('grep', 'recursive_opts', [])
	call denite#custom#var('grep', 'pattern_opt', [])
	call denite#custom#var('grep', 'separator', ['--'])
	call denite#custom#var('grep', 'final_opts', [])

  let g:denite_win_width_percent = 0.85
  let g:denite_win_height_percent = 0.7
  call denite#custom#option('default', {
    \ 'split': 'floating',
    \ 'winwidth': float2nr(&columns * g:denite_win_width_percent),
    \ 'wincol': float2nr((&columns - (&columns * g:denite_win_width_percent)) / 2),
    \ 'winheight': float2nr(&lines * g:denite_win_height_percent),
    \ 'winrow': float2nr((&lines - (&lines * g:denite_win_height_percent)) / 2),
  \ })
'''

[[plugins]]
repo = 'nixprime/cpsm'
build = 'env PY3=ON ./install.sh'
on_source = ['denite.nvim']

#########################################
# Syntac highlight for Vue.js plugin
#########################################
[[plugins]]
repo = 'posva/vim-vue'
hook_add = '''
au BufRead,BufNewFile *.vue setlocal filetype=vue
au BufWinEnter *.vue exe ':syntax sync fromstart'
'''
on_ft = ['vue']

#########################################
# Auto coding settings
#########################################
[[plugins]]
repo = 'cohama/lexima.vim'
hook_add = '''
let g:lexima_enable_newline_rules	= 1
let g:lexima_enable_space_rules = 1

" If b:lexima_disabled is 1, lexima plugin will not work.
nnoremap <silent> <space>2 :call <SID>toggle_auto_coding()<CR>
function! s:toggle_auto_coding()
    if exists("b:lexima_disabled")
        if b:lexima_disabled
            let b:lexima_disabled = 0
            echo 'lexima is enabled'
        else
            let b:lexima_disabled = 1
            echo 'lexima is disabled'
        endif
    else
        let b:lexima_disabled = 1
        echo 'lexima is disabled'
    endif

endfunction
'''

hook_post_source = '''
" --------- For comma rule ----------
call lexima#add_rule({
\   "at" : '\%# ',
\   "char" : ",",
\   "input" : ",",
\})

call lexima#add_rule({
\   "at" : '\%#',
\   "char" : ",",
\   "input" : ",<Space>",
\})

call lexima#add_rule({
\   "at" : ', \%#',
\   "char" : '<Space>',
\   "input" : "",
\})

" -------- For parenthesis rule --------
" ----- Input -----
call lexima#add_rule({
\   "char" : '{',
\   "at" : '[A-Za-z]\%#',
\   "input" : ' {}<Left>',
\})

call lexima#add_rule({
\   "char" : '{',
\   "at" : ')\%#',
\   "input" : ' {}<Left>',
\})

call lexima#add_rule({
\   "char" : '{',
\   "at" : '>\%#',
\   "input" : ' {}<Left>',
\})

call lexima#add_rule({
\   "char" : '{',
\   "at" : ':\%#',
\   "input" : ' {}<Left>',
\})
'''
on_i = 1

#########################################
# For highlight toml file
#########################################
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
