#########################################
# Syntax checker
#########################################
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''

" For airline
let g:airline#extensions#ale#enabled = 1

" Always display sign_column
let g:ale_sign_column_always = 1

" Lint timing settings
let g:ale_lint_on_text_changed = 0
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1

" Delay settings
let g:ale_lint_delay = 10

" Statusline mark
let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
let g:ale_sign_error = 'x'
let g:ale_sign_warning = '?'

" Fix settings
let g:ale_fix_on_save = 1

" Specify linters
let g:ale_linters = {
  \ 'javascript': ['standard'],
  \ 'vue': ['eslint','vls'],
  \ 'python': ['pylint'],
\ }
let g:ale_python_flake8_use_global = 1
let g:ale_linter_aliases = {'vue': ['vue', 'javascript']}

" Specify fixers
let g:ale_fixers = {
  \ 'javascript': ['eslint'],
  \ 'python': ['autopep8', 'isort'],
\ }

'''

hook_post_source = '''

nmap <silent> [call]k <Plug>(ale_previous_wrap)
nmap <silent> [call]j <Plug>(ale_next_wrap)
nmap <silent> [call]o <Plug>(ale_toggle)
nmap <silent> [call]d <Plug>(ale_detail)

'''
on_ft = ['python', 'javascript', 'vue']

#########################################
#Sass
#########################################
[[plugins]]
repo = 'AtsushiM/search-parent.vim'
on_ft = ['sass', 'scss']

[[plugins]]
repo = 'AtsushiM/sass-compile.vim'
hook_post_source = '''
nnoremap <silent> [autoCompile] :SassCompile<CR>
'''
on_ft = ['sass', 'scss']

#########################################
# Syntac highlight for Vue.js plugin
#########################################
[[plugins]]
repo = 'posva/vim-vue'
hook_add = '''
au FileType vue syntax sync fromstart
au BufRead,BufNewFile *.vue setlocal filetype=vue
'''
on_ft = ['vue']

#########################################
# Syntac highlight for pug plugin
#########################################
[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['pug', 'vue']

#########################################
# Syntac highlight for scss plugin
#########################################
[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = ['scss', 'vue']
