[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
let g:python3_host_prog = $PYENV_ROOT . '/shims/python3'
let mapleader = "\<Space>"
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
"<Nop>は無効化を意味する
nmap [denite] <Nop>
map s [denite]

nmap <silent> [denite]p :<C-u>Denite file_rec -highlight-mode-insert=Search<CR>
nmap <silent> [denite]o :<C-u>DeniteBufferDir file_rec -highlight-mode-insert=Search<CR>
nmap <silent> [denite]b :<C-u>Denite buffer -highlight-mode-insert=Search<CR>
nmap <silent> [denite]y :<C-u>Denite file_old -highlight-mode-insert=Search<CR>
nmap <silent> [denite]s :<C-u>Denite line -auto-preview -highlight-mode-insert=Search<CR>
nmap <silent> [denite]h :<C-u>Denite help -highlight-mode-insert=Search<CR>
nmap <silent> [denite]w :<C-u>Denite -auto-preview -highlight-mode-insert=Search grep<CR>
call denite#custom#map('insert', 'jj', '<denite:enter_mode:normal>', 'noremap')
call denite#custom#source('file_rec', 'matchers', ['matcher_fuzzy','matcher_ignore_globs'])
" customize ignore globs
call denite#custom#filter('matcher_ignore_globs', 'ignore_globs',
      \ [
      \ '.git/', '.gomi/',
      \ 'images/', '*.o', '*.make',
      \ '*.min.*',
      \ 'img/', 'fonts/'])
'''

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
let g:winresizer_start_key = '<C-T>'
'''

[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
let g:user_emmet_mode='ni'
let g:user_emmet_install_gloabal = 0
let g:user_emmet_leader_key='<C-Y>'
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
nmap [figitive] <Nop>
map <C-g> [figitive]
nmap <silent> [figitive]s :<C-u>Gstatus<CR>
nmap <silent> [figitive]d :<C-u>Gdiff<CR>
nmap <silent> [figitive]b :<C-u>Gblame<CR>
nmap <silent> [figitive]l :<C-u>Glog<CR>
nmap <silent> [figitive]r :<C-u>Gread<CR>
nmap <silent> [figitive]a :<C-u>Gwrite<CR>
'''

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
hook_add = '''
let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "✹",
    \ "Staged"    : "✚",
    \ "Untracked" : "✭",
    \ "Renamed"   : "➜",
    \ "Unmerged"  : "═",
    \ "Deleted"   : "✖",
    \ "Dirty"     : "✗",
    \ "Clean"     : "✔︎",
    \ 'Ignored'   : '☒',
    \ "Unknown"   : "?"
    \ }

    map <C-b> :NERDTreeToggle<CR>
'''
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
"Apply linter when open new files
let g:ale_lint_on_enter = 1

"To be able to use on vim-airline
let g:airline#extensions#ale#enabled = 1

"Display sinbol columns any time
let g:ale_sign_column_always = 1

"Display warning count and number of errors
let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']

"Not lint on changed text
let g:ale_lint_on_text_changed = 0
let g:ale_lint_on_insert_leave = 1
let g:ale_fix_on_save = 1

nmap <Leader> <Nop>
nmap <silent> <Leader>k <Plug>(ale_previous_wrap)
nmap <silent> <Leader>j <Plug>(ale_next_wrap)
nmap <silent> <Leader>o <Plug>(ale_toggle)
'''
