[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
let g:python3_host_prog = $PYENV_ROOT . '/shims/python3'
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
"<Nop>は無効化を意味する
nmap [denite] <Nop>
map s [denite]

nmap <silent> [denite]p :<C-u>Denite file_rec -highlight-mode-insert=Search<CR>
nmap <silent> [denite]o :<C-u>DeniteBufferDir file_rec -highlight-mode-insert=Search<CR>
nmap <silent> [denite]b :<C-u>Denite buffer -highlight-mode-insert=Search<CR>
nmap <silent> [denite]y :<C-u>Denite file_old -highlight-mode-insert=Search<CR>
nmap <silent> [denite]s :<C-u>Denite line -auto-preview -highlight-mode-insert=Search<CR>
nmap <silent> [denite]h :<C-u>Denite help -highlight-mode-insert=Search<CR>
nmap <silent> [denite]w :<C-u>Denite -auto-preview -highlight-mode-insert=Search grep<CR>
call denite#custom#map('insert', 'jj', '<denite:enter_mode:normal>', 'noremap')
" customize ignore globs
call denite#custom#source('file_rec', 'matchers', ['matcher_fuzzy','matcher_ignore_globs'])
call denite#custom#filter('matcher_ignore_globs', 'ignore_globs',
      \ [
      \ '.git/', '.gomi/',
      \ 'images/', '*.o', '*.make',
      \ '*.min.*',
      \ 'img/', 'fonts/'])
'''

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
let g:winresizer_start_key = '<C-T>'
'''
