# ===== Color themes =====
# [[plugins]]
# repo = 'morhetz/gruvbox'
# merged = 0
# trusted = 1
# hook_add = '''
# autocmd VimEnter * nested colorscheme gruvbox
# set background=dark
# let g:gruvbox_contrast_dark = 'hard'
# '''

# [[plugins]]
# repo = 'rakr/vim-one'
# merged = 0
# trusted = 1
# hook_add = '''
# autocmd VimEnter * nested colorscheme one
# set background=dark
# let g:one_allow_italics = 1
# '''

# [[plugins]]
# repo = 'cocopon/iceberg.vim'
# merged = 0
# trusted = 1
# hook_add = '''
# autocmd VimEnter * nested colorscheme iceberg
# '''

# [[plugins]]
# repo = 'haishanh/night-owl.vim'
# merged = 0
# trusted = 1
# hook_add = '''
# autocmd VimEnter * nested colorscheme night-owl
# set background=dark
# '''

# [[plugins]]
# repo = 'jonathanfilip/vim-lucius'
# merged = 0
# trusted = 1
# hook_add = '''
# autocmd VimEnter * nested colorscheme lucius
# set background=dark

# autocmd User CocOpenFloat
#   \ if exists('w:float')
#   \ |   hi CocFloating guibg=#616161 guifg=NONE
#   \ | endif
# '''

[[plugins]]
repo = 'dracula/vim'
merged = 0
trusted = 1
hook_add = '''
autocmd VimEnter * nested colorscheme dracula
set background=dark
'''
