# ===== Status line =====
[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
" use powerline-font
set laststatus=2
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_idx_mode = 1
let g:airline#extensions#whitespace#mixed_indent_algo = 1
let g:airline_theme='base16_spacemacs'

if !exists('g:airline_symbols')
let g:airline_symbols = {}
endif
'''

# ===== Color themes =====
# [[plugins]]
# repo = 'morhetz/gruvbox'
# merged = 0
# hook_add = '''
# autocmd VimEnter * nested colorscheme gruvbox
# set background=dark
# let g:gruvbox_contrast_dark = 'hard'
# '''

# [[plugins]]
# repo = 'rakr/vim-one'
# merged = 0
# hook_add = '''
# autocmd VimEnter * nested colorscheme one
# set background=dark
# let g:one_allow_italics = 1
# '''

# [[plugins]]
# repo = 'cocopon/iceberg.vim'
# merged = 0
# hook_add = '''
# autocmd VimEnter * nested colorscheme iceberg
# '''

# [[plugins]]
# repo = 'haishanh/night-owl.vim'
# merged = 0
# hook_add = '''
# autocmd VimEnter * nested colorscheme night-owl
# set background=dark
# '''

[[plugins]]
repo = 'jonathanfilip/vim-lucius'
merged = 0
hook_add = '''
autocmd VimEnter * nested colorscheme lucius
set background=dark

autocmd User CocOpenFloat
  \ if exists('w:float')
  \ |   hi CocFloating guibg=#616161 guifg=NONE
  \ | endif
'''
